service: tastyworks-challenge

plugins:
  - serverless-plugin-optimize
  - serverless-pseudo-parameters

package:
  individually: true
  
provider:
  name: aws
  runtime: nodejs10.x

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:Scan
        - dynamodb:GetItem
      Resource:
        - arn:aws:dynamodb:#{AWS::Region}:#{AWS::AccountId}:table/stocksTable

functions:
  getStocks:
    handler: handler.getStocks
    events:
      - http: 
          path: /stocks
          method: get
          cors: true
    environment:
      stocksTableName: stocksTable

resources:
  Resources:
    stocksTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: stocksTable
        AttributeDefinitions:
          - AttributeName: "stockId"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "stockId"
            KeyType: "HASH"
        BillingMode: PAY_PER_REQUEST
    